In [1]:
import numpy as np

In [2]:
# create a 2d vector as an array
x = np.array([3,4])

In [3]:
import math 

# implement a method to compute the magnitude of a vector
def vector_norm(vector):
    squares = [elements**2 for elements in vector]
    return math.sqrt(sum(squares))

In [4]:
# compute the norm of the vector
vector_norm(x)

5.0

In [5]:
# let's use the linear algebra package to compute the same
from numpy import linalg 
linalg.norm(x)

5.0

### NumPy linear algebra functions
https://numpy.org/doc/stable/reference/routines.linalg.html

In [6]:
# create another vector y
y = np.array([2,3])

In [7]:
# compute the dot product of x and y
np.dot(x,y)

18

In [8]:
# check if dot product is commutative
np.dot(x,y) == np.dot(y,x)

True

In [9]:
# create a matrix of shape 2x2
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [10]:
# create an array and reshape it to a matrix
x = np.array([2,4,5]).reshape(-1,1)
print(x)

[[2]
 [4]
 [5]]


In [11]:
# perform matrix multiplation
z = np.matmul(A,x)
print(z)

[[25]
 [58]]


In [12]:
A.shape, x.shape, z.shape

((2, 3), (3, 1), (2, 1))

In [13]:
# create more matrices
D = np.array([
            [2, 3, 5, 7],
            [11, 13, 17, 19],
            [23, 29, 31, 37]
])

A = np.array([[3], [4], [5]])

In [14]:
A

array([[3],
       [4],
       [5]])

In [15]:
D.shape,A.shape

((3, 4), (3, 1))

In [16]:
# attempt to perform an invalid matrix operation
try:
    np.matmul(D, A)
except ValueError as e:
    print("ValueError", e)

ValueError matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)


In [17]:
# create matrix F 3x2
F = np.array([[5,2],
              [4,1],
              [9,3]])
print(F)

[[5 2]
 [4 1]
 [9 3]]


In [18]:
# create a matrix A 2x3
A = np.array([
        [10, 20, 30],
        [40, 50, 60]
])
print(A)

[[10 20 30]
 [40 50 60]]


In [19]:
# perform a dot product with the rows and colums (equivalent to matmul??)
A.dot(F)

array([[400, 130],
       [940, 310]])

In [20]:
# check if the matmul gives the same values
np.matmul(A, F)

array([[400, 130],
       [940, 310]])

In [21]:
# what if we swap the operands? 
F.dot(A)

array([[130, 200, 270],
       [ 80, 130, 180],
       [210, 330, 450]])

In [22]:
# Is that also an equivalent of matmul?
np.matmul(F, A)

array([[130, 200, 270],
       [ 80, 130, 180],
       [210, 330, 450]])

In [23]:
# let's study the transpose.
A

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [25]:
# create another square matrix
E = np.array([[1,1.5], [0,1]])
print(E)

[[1.  1.5]
 [0.  1. ]]


In [26]:
# let's compute the inverse of the matrix
E_inv = linalg.inv(E)
print(E_inv)

[[ 1.  -1.5]
 [ 0.   1. ]]


In [27]:
# if we multiple the E with its inverse, we should get an identity matrix
np.matmul(E, E_inv) 

array([[1., 0.],
       [0., 1.]])

In [28]:
# check if we did get an identity matrix.
np.matmul(E, E_inv)  == np.eye(2)

array([[ True,  True],
       [ True,  True]])

In [31]:
b = np.array([[1],[3,2],[2,3,4]])

C:\Users\gowtham.balachan\AppData\Local\Temp\ipykernel_40284\3267878084.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[1],[3,2],[2,3,4]])


In [32]:
b

array([list([1]), list([3, 2]), list([2, 3, 4])], dtype=object)

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

How to extract all numbers between a given range from a numpy array?


In [34]:
# Get all numbers between 8 and 12
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [35]:
index = np.where(np.logical_and(a >= 8, a <=12))
print(index)

(array([3, 4], dtype=int64),)


In [36]:
a[index]

array([ 9, 10])

In [37]:
c = np.array([1,2,3])

Compute the mean, median and standard deviation of an array

In [38]:
mu, med, sd = np.mean(c), np.median(c), np.std(c)
print(mu, med, sd)

2.0 2.0 0.816496580927726


In [40]:
# compute s.d by the formula
math.sqrt(sum([(item - mu)**2 for item in c])/len(c))

0.816496580927726

In [41]:
# compute the standardized variables x - mu / sigma.
d = (c - mu)/sd
print(d)

[-1.22474487  0.          1.22474487]


In [42]:
# mean should be 0 and sd should be 1 for standardized variables.
print(np.mean(d), np.std(d))

0.0 0.9999999999999999


In [43]:
a = [1,2,3,4]

In [50]:
a[-1:-2]

[]